# ROUTES
route.setup: "âš™ï¸ Setup"
route.tutorial: "ğŸ“– Tutorial"
route.tutorial.continue: "ğŸ“– Continua tutorial"
route.exploration: "â­•ï¸ Esplorazione"
route.player: "ğŸ‘¨ğŸ¼â€ğŸš€ Player"
route.player.guild: "ğŸ’¢ Gilda"
route.player.party: "ğŸ”° Party"
route.player.party.create: "ğŸ”° Crea Party"
route.player.party.leave: "ğŸƒâ€â™‚ï¸ Abbandona Party"
route.player.party.add_player: "â• Aggiungi al Party"
route.player.party.remove_player: "â– Rimuovi dal Party"
route.player.inventory: "ğŸ“¦ Cargo"
route.player.inventory.resources: "ğŸ’  Risorse"
route.player.inventory.items: "ğŸ”© Oggetti"
route.player.inventory.equip: "ğŸ›¡ Equipaggiamento"
route.player.inventory.packs: "ğŸ Pacchetti"
route.player.achievements: "ğŸ¯ Achievements"
route.ability: "ğŸ§¬ AbilitÃ "
route.hunting: "âš”ï¸ Caccia"
route.darkmerchant: "ğŸ•µğŸ¾â€â™‚ï¸ Mercante Oscuro"
route.ship: "ğŸš€ Nave"
route.ship.travel: "ğŸ”­ Viaggio"
route.ship.travel.finding: "ğŸ“¡ Ricerca"
route.ship.travel.rescue: "ğŸ§° Soccorso"
route.ship.travel.favorite: "â­ï¸ Lista Preferiti"
route.ship.travel.manual: "ğŸ§­ Manuale"
route.ship.warehouse: "Deposito"
route.ship.rests: "ğŸ’¤ Riposa"
route.ship.laboratory: "ğŸ§ª Laboratorio"
route.menu: "BoardSystem"
route.menu.npc: "ğŸ› Piazza"
route.force.die: "Delete"
route.banned: "Banned"
route.planet: "ğŸŒ Pianeta"
route.planet.bookmark.add: "â­ï¸ Aggiunti ai preferiti"
route.planet.bookmark.remove: "â­ï¸ Rimuovi dai preferiti"
route.conqueror: "ğŸš© Conquistatore"

# Safe planet
route.safeplanet.coalition.daily_reward: "ğŸ“¦ Ricompensa giornaliera"
route.safeplanet.bank: "ğŸ¦ Banca"
route.safeplanet.crafter: "ğŸ›  Armaiolo"
route.safeplanet.crafter.create: "ğŸ›  Realizza"
route.safeplanet.crafter.repair: "âœ¨ Ripara Arma"
route.safeplanet.crafter.decompose: "â™»ï¸ Smonta"
route.safeplanet.dealer: "âš–ï¸ Mercante"
route.safeplanet.accademy: "â›© Accademia"
route.safeplanet.hangar: "ğŸ— Hangar"
route.safeplanet.relax: "ğŸ² Svago"
route.safeplanet.relax.threecard: "ğŸƒ 3 Carte"
route.safeplanet.hangar.ships: "ğŸš€ Il tuo deposito"
route.safeplanet.hangar.repair: "âœ¨ Ripara Nave"
route.safeplanet.hangar.create: "ğŸ’¸ Compra"
route.safeplanet.coalition: "ğŸ’ˆ Coalizione"
route.safeplanet.coalition.mission: "ğŸ¢ Centro Missioni"
route.safeplanet.coalition.titan: "ğŸ‘ Titani"
route.safeplanet.coalition.expansion: "ğŸ’« Espansione"
route.safeplanet.coalition.research: "ğŸ”¬ Ricerca"
route.safeplanet.coalition.research.donation: "ğŸ— Dona risorse"
route.safeplanet.coalition.protectors: "ğŸ’¢ Protettori"
route.safeplanet.coalition.statistics: "ã€½ï¸ Top Esploratori"
route.safeplanet.coalition.protectors.create: "â• Crea"
route.safeplanet.coalition.protectors.join: "ğŸ” Cerca"
route.safeplanet.coalition.protectors.leave: "ğŸƒâ€â™‚ï¸ Abbandona Gilda"
route.safeplanet.coalition.protectors.add_player: "â• Aggiungi esploratore"
route.safeplanet.coalition.protectors.remove_player: "â– Rimuovi esploratore"
route.safeplanet.coalition.protectors.change_leader: "ğŸ‘‘ Cambia Leader"
route.safeplanet.coalition.protectors.switch: "ğŸ‘€ Cambia VisibilitÃ "

# Titan planet
route.titanplanet.tackle: "Affronta ğŸ‘ Titano"

# Breaker
route.breaker.continue: "Continua"
route.breaker.menu: "â¬…ï¸ Torna al menu"
route.breaker.back: "â¬…ï¸ Indietro"
route.breaker.clears: "â¬…ï¸ Abbandona"

#INFO
route.info: "ğŸ—’ Info"