---
#ROUTES
route.setup: "âš™ï¸ Setup"
route.tutorial: "ğŸ“– Tutorial"
route.tutorial.continue: "ğŸ“– Continue tutorial"
route.exploration: "â­•ï¸ Exploration"
route.player: "ğŸ‘¨ğŸ¼â€ğŸš€ Player"
route.player.guild: "ğŸ’¢ Guild"
route.player.party: "ğŸ”° Party"
route.player.party.create: "ğŸ”° Create Party"
route.player.party.leave: "ğŸƒâ€â™‚ï¸ Leave Party"
route.player.party.add_player: "â•Add to Party"
route.player.party.remove_player: "â– Remove from Party"
route.player.inventory: "ğŸ’ Inventory"
route.player.inventory.resources: "ğŸ’  Resources"
route.player.inventory.items: "ğŸ”© Items"
route.player.inventory.equip: "ğŸ›¡ Equipment"
route.player.inventory.packs: "ğŸ Packs"
route.player.achievements: "ğŸ¯ Achievements"
route.ability: "ğŸ§¬ Ability"
route.hunting: "âš”ï¸ Hunting"
route.darkmerchant: "ğŸ•µğŸ¾â€â™‚ï¸ Dark Merchant"
route.ship: "ğŸš€ Ship"
route.ship.travel: "ğŸ”­ Travel"
route.ship.travel.finding: "ğŸ“¡ Find"
route.ship.travel.rescue: "ğŸ§° Rescue"
route.ship.travel.favorite: "â­ï¸ Favourites List"
route.ship.travel.manual: "ğŸ§­ Manual"
route.ship.warehouse: "Warehouse"
route.ship.rests: "ğŸ’¤ Rest"
route.ship.laboratory: "ğŸ§ª Laboratory"
route.menu: "BoardSystem"
route.menu.npc: "ğŸ› Plaza"
route.force.die: "Delete"
route.banned: "Banned"
route.planet: "ğŸŒ Planet"
route.planet.bookmark.add: "â­ï¸ Add to favourite"
route.planet.bookmark.remove: "â­ï¸ Remove from favourites"
route.planet.conqueror: "ğŸš© Conqueror"
route.planet.domain: "ğŸ´ Domination"
#Safe planet
route.safeplanet.coalition.daily_reward: "ğŸ“¦ Daily reward"
route.safeplanet.bank: "ğŸ¦ Bank"
route.safeplanet.crafter: "ğŸ›  Gunsmith"
route.safeplanet.crafter.create: "ğŸ›  Create"
route.safeplanet.crafter.repair: "âœ¨ Repair Weapon"
route.safeplanet.crafter.decompose: "â™»ï¸ Disassemble"
route.safeplanet.accademy: "â›© Academy"
route.safeplanet.hangar: "ğŸ— Hangar"
route.safeplanet.relax: "ğŸ² Relax"
route.safeplanet.relax.threecard: "ğŸƒ 3 Cards"
route.safeplanet.hangar.ships: "ğŸš€ Your warehouse"
route.safeplanet.hangar.repair: "âœ¨ Repair Ship"
route.safeplanet.hangar.create: "ğŸ’¸ Buy"
#Market
route.safeplanet.market: "ğŸ¬ Market"
route.safeplanet.market.dealer: "âš–ï¸ Merchant"
route.safeplanet.market.gift: "ğŸ§§ Gift"
route.safeplanet.market.shareholder: "ğŸ•‹ Bazar (WIP)"
#Coalition
route.safeplanet.coalition: "ğŸ’ˆ Coalition"
route.safeplanet.coalition.mission: "ğŸ¢ Mission Center"
route.safeplanet.coalition.titan: "ğŸ‘ Titans"
route.safeplanet.coalition.expansion: "ğŸ’« Expansion"
route.safeplanet.coalition.research: "ğŸ”¬ Research"
route.safeplanet.coalition.research.donation: "ğŸ— Donate resources"
route.safeplanet.coalition.protectors: "ğŸ’¢ Guardians"
route.safeplanet.coalition.statistics: "ã€½ï¸ Top Explorers"
route.safeplanet.coalition.protectors.create: "â• Create"
route.safeplanet.coalition.protectors.join: "ğŸ” Find"
route.safeplanet.coalition.protectors.leave: "ğŸƒâ€â™‚ï¸ Leave Guild"
route.safeplanet.coalition.protectors.add_player: "â• Add explorer"
route.safeplanet.coalition.protectors.remove_player: "â– Remove explorer"
route.safeplanet.coalition.protectors.change_leader: "ğŸ‘‘ Change Leader"
route.safeplanet.coalition.protectors.switch: "ğŸ‘€ Change privacy"
route.safeplanet.coalition.protectors.change_name: "ğŸ–‹ Change name"
route.safeplanet.coalition.protectors.change_tag: "âœ’ï¸ Change tag"
#Titan planet
route.titanplanet.tackle: "Take on ğŸ‘ Titan"
#Breaker
route.breaker.continue: "Continue"
route.breaker.menu: "â¬…ï¸ Back to menu"
route.breaker.back: "â¬…ï¸ Back"
route.breaker.clears: "â¬…ï¸ Leave"
#INFO
route.info: "ğŸ—’ Rules"
